version: 2.1 
orbs:
  python: circleci/python@2.0.3
jobs:
  testing: 
    executor: python/default
    steps:
      - checkout
      - python/install-packages: 
          pkg-manager: pip
      - run:
         name: run tests
         command: python main.py
workflows:
  build_and_test:
   jobs:
     - testing 
     

